#!/bin/bash

echo "machine ${CI_NETRC_MACHINE}" > "${HOME}/.netrc"
echo "login ${CI_NETRC_USERNAME}" >> "${HOME}/.netrc"
echo "password ${CI_NETRC_PASSWORD}" >> "${HOME}/.netrc"

set -ex

WORKDIR=`pwd`
LOCAL_REPO="/var/git_local/$DRONE_REPO_NAME"

echo "Workspace: $WORKDIR"
echo "Local cahched repo path: $LOCAL_REPO"

mkdir -p $LOCAL_REPO
cd $LOCAL_REPO
if [[ -d .git ]]; then
    echo 'Local cached git repo exists.'
else
    echo 'Local cached git repo dose not exist. Start init...'
    git init
    git remote add origin $DRONE_GIT_HTTP_URL
    echo 'Done.'
fi

echo 'Updating local cahched repo...'

retry_times=0
until [ $retry_times -ge 20 ]; do
    git fetch origin ${DRONE_COMMIT_SHA} && git checkout ${DRONE_COMMIT_SHA} && break
    retry_times=$[$retry_times+1]
    sleep 10
done

echo 'Done.'

echo 'Checkout commit from local cahched repo...'

cd $WORKDIR
if [[ ! -d .git ]]; then
    git init
    git remote add origin $DRONE_GIT_HTTP_URL
    git remote add local-source $LOCAL_REPO/.git
fi
# overwrite old settings
git remote set-url local-source $LOCAL_REPO/.git

git fetch local-source ${DRONE_COMMIT_SHA}
git reset ${DRONE_COMMIT_SHA} --hard
echo 'Done.'

