#!/bin/bash

echo "machine ${CI_NETRC_MACHINE}" > "${HOME}/.netrc"
echo "login ${CI_NETRC_USERNAME}" >> "${HOME}/.netrc"
echo "password ${CI_NETRC_PASSWORD}" >> "${HOME}/.netrc"

set -ex

WORKDIR=`pwd`
LOCAL_REPO="/var/git_local/$DRONE_REPO_NAME"

echo "Workspace: $WORKDIR"
echo "Local cahched repo path: $LOCAL_REPO"

cd $LOCAL_REPO
if [[ -d .git ]]; then
    echo 'Local cached git repo exists.'
else
    echo 'Local cached git repo dose not exist. Start init...'
    git init
    git remote add origin $DRONE_GIT_HTTP_URL
    echo 'Done.'
fi

echo 'Updating local cahched repo...'
git fetch --all
git checkout $DRONE_COMMIT_BRANCH
git reset --hard origin/$DRONE_COMMIT_BRANCH
git checkout $DRONE_COMMIT
echo 'Done.'

echo 'Checkout commit from local cahched repo...'

cd $WORKDIR
if [[ ! -d .git ]]; then
    git init
    git remote add origin $LOCAL_REPO
fi

git clean -f
git fetch --all
git checkout $DRONE_COMMIT_BRANCH
git reset --hard origin/$DRONE_COMMIT_BRANCH
git checkout $DRONE_COMMIT
echo 'Done.'

